### ISSUE TITLE
404 error when changing to a branch with / in its name

### ISSUE THREAD

**Issue by imella** [deliverybot/deliverybot#27]
In the deliverybot UI if I change to a branch with a `/` in its name it throws a 404 error (ex: `feat/new-amazing-feature`)

<img width="908" alt="Screen Shot 2020-01-28 at 16 15 21" src="https://user-images.githubusercontent.com/741631/73297450-5e643680-41ea-11ea-84ad-c48c784d6403.png">

Selecting a branch with `/`

<img width="1142" alt="Screen Shot 2020-01-28 at 16 15 49" src="https://user-images.githubusercontent.com/741631/73297561-8eabd500-41ea-11ea-9284-ff070a648ff8.png">

404 error

<img width="1680" alt="Screen Shot 2020-01-28 at 16 16 24" src="https://user-images.githubusercontent.com/741631/73297694-ca469f00-41ea-11ea-98c8-4cf0a4e0d6c8.png">

**Comment by colinjfw** [comment]
@imella this should be fixed now.

**Comment by imella** [comment]
@colinjfw Thanks! But I'm still having the same issue (I see the encoded url though), maybe it's related to something else?

**Comment by colinjfw** [comment]
@imella I think I've fixed it this time :)

**Comment by imella** [comment]
@colinjfw Cool! Just one little thing, it's working for names with just one `/`. If there are multiple ones only the first is encoded and the rest not, resulting in a 404 (but now the 404 doesn't have a broken design 😃 )

**Comment by colinjfw** [comment]
🤦‍♂

**Comment by colinjfw** [comment]
@imella really appreciate your patience with this, I think I've finally figured this one out.

**Comment by imella** [comment]
@colinjfw It's still happening.
Take this branch name for example 
```
dependabot/npm_and_yarn/google-cloud/functions-framework-1.4.0
```
 it's getting encoded like this 
```
dependabot%20npm_and_yarn/google-cloud/functions-framework-1.4.0
```
